INSERT INTO CAR (BRAND, MODEL, VERSION) VALUES ('BMW', '320d', 1);
INSERT INTO CAR (BRAND, MODEL, VERSION) VALUES ('Audi', 'A3 2.0 TDI', 0);
INSERT INTO CAR (BRAND, MODEL, VERSION) VALUES ('Mercedes', 'A 220d', 0);

INSERT INTO FIELD (F_STRING) VALUES ('text');