CREATE TABLE CAR (
	ID BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    BRAND VARCHAR(255) NOT NULL,
    MODEL VARCHAR(255),
    VERSION INTEGER,
    PRIMARY KEY (ID)
);

CREATE TABLE FIELD (
	ID BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    F_STRING VARCHAR(255) NOT NULL,
--    F_BOOLEAN BOOLEAN,
--    F_BYTE TINYINT,
    F_SHORT SMALLINT, 
    F_INT INTEGER,
    F_LONG BIGINT,
    F_FLOAT REAL,
    F_DOUBLE DOUBLE,
    F_BIGDECIMAL DECIMAL(10,3),
    F_CLOB CLOB,
    F_BLOB BLOB,
    F_DATE DATE,
    F_TIME TIME,
    F_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (ID)
);
